[project]
name = "cli-backend-server"
version = "0.1.0"
description = "A CLI backend server"
readme = "README.md"
authors = [
    { name = "Benjamin Bugl", email = "benjamin.bugl@gmx.net" }
]
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = ["bpython"]

[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 120
